- name: create app
  shell: dokku apps:create wiki
  args:
    creates: /home/dokku/wiki

- name: set config
  shell: dokku config:set wiki USERNAME={{wiki_user}} PASSWORD={{wiki_password}} BASE_URL={{wiki_base}} GIN_MODE=release

- name: set buildpack
  shell: dokku config:set wiki GO15VENDOREXPERIMENT=1 BUILDPACK_URL=https://github.com/heroku/heroku-buildpack-go.git
