- name: check dokku availability
  shell: which dokku | grep dokku
  ignore_errors: true
  register: dokku

- name: download bootstrap script
  get_url:
    url: https://raw.githubusercontent.com/dokku/dokku/{{dokku_version}}/bootstrap.sh
    dest: /root/bootstrap.sh
  when: dokku|failed

- name: clean key from comments
  shell: 'sed -i.bak "/^[[:blank:]]*#/d;s/#.*//" /root/.ssh/authorized_keys'

- name: debconf settings
  shell: 'echo "dokku {{ item }}" | debconf-set-selections'
  with_items:
    - "dokku/web_config boolean false"
    - "dokku/vhost_enable boolean true"
    - "dokku/hostname string iad.zhdk.ch"
    - "dokku/key_file string /root/.ssh/authorized_keys"
  when: dokku|failed

- name: install dokku
  command: bash /root/bootstrap.sh
  environment:
    DOKKU_TAG: "{{dokku_version}}"
  when: dokku|failed

- name: check mongo plugin availability
  shell: dokku plugin | grep mongo
  ignore_errors: true
  register: dokku_mongo

- name: check redis plugin availability
  shell: dokku plugin | grep redis
  ignore_errors: true
  register: dokku_redis

- name: install mongo plugin
  shell: dokku plugin:install https://github.com/dokku/dokku-mongo.git mongo
  when: dokku_mongo|failed

- name: install redis plugin
  shell: dokku plugin:install https://github.com/dokku/dokku-redis.git redis
  when: dokku_redis|failed

- name: allow http
  ufw: rule=allow port=80 proto=tcp
